title: Research & Technology Overview
author: Wilkie Olin-Ammentorp
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Summaries of recent research projects & technology, (c) 2021 Wilkie Olin-Ammentorp
# social links
github_username:  wilkieolin # DO NOT include the @ character, or else the build will fail!
theme: minima
excerpt_separator: <!--more-->

show_excerpts: true # set to false to remove excerpts on the homepage